name: Vargas Photography Agency
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp.server: ftp.vargasjenkinsphotography.com
          ftp.username: ${{ secrets.FTP_USERNAME }}
          ftp.password: ${{ secrets.FTP_PASSWORD }}
